### ISSUE TITLE
Put the list of cohorts in descending order of subscription_start_date

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-internship#30]
This way, the most recent cohort stays on top.

**Comment by mathieuzen** [comment]
Probably the filter logic should be moved from the template to the model as specified in [CONTRIBUTING_DOC](https://github.com/uclouvain/osis-internship/blob/master/.github/CONTRIBUTING.md#vue-).

Could you confirm it has to be done differently ?

**Comment by htmfilho** [comment]
No, no. This is a presentation issue, not a business issue. It is good to see the solution in the presentation layer. Good job!
